const BOARD_DATA = [
  {
    id: 1,
    title: "오늘 혈압 측정 결과 공유드립니다",
    content:
      "아침에 측정한 혈압이 130/80 정도였는데 괜찮은 수치인지 궁금합니다...",
    author: "김환자",
    createdAt: "2024-08-04T10:30:00",
    views: 124,
    comments: 8,
    likes: 15,
    category: "건강체크",
    isHot: true,
  },
  {
    id: 2,
    title: "복용 중인 약물 부작용 관련 질문",
    content:
      "최근에 처방받은 약을 복용하고 있는데 어지러움 증상이 있어서 문의드립니다",
    author: "이보호자",
    createdAt: "2024-08-04T09:15:00",
    views: 89,
    comments: 12,
    likes: 7,
    category: "복약상담",
    isHot: false,
  },
  {
    id: 3,
    title: "당뇨 환자 식단 관리 팁 공유",
    content:
      "당뇨 관리하면서 도움이 되었던 식단과 운동 방법들을 정리해서 올려드려요",
    author: "박건강",
    createdAt: "2024-08-04T08:45:00",
    views: 256,
    comments: 23,
    likes: 41,
    category: "생활정보",
    isHot: true,
  },
  {
    id: 4,
    title: "병원 예약 시스템 사용법 문의",
    content: "모바일로 병원 예약하는 방법을 잘 모르겠어서 도움 요청드립니다",
    author: "정신규",
    createdAt: "2024-08-04T07:20:00",
    views: 67,
    comments: 5,
    likes: 3,
    category: "이용문의",
    isHot: false,
  },
  {
    id: 5,
    title: "오늘 운동 인증! 산책 30분 완료",
    content: "날씨가 좋아서 공원에서 산책하고 왔어요. 사진도 함께 올립니다~",
    author: "김활력",
    createdAt: "2024-08-03T18:30:00",
    views: 45,
    comments: 7,
    likes: 12,
    category: "운동인증",
    isHot: false,
  },
  {
    id: 6,
    title: "정기검진 결과 해석 도움 요청",
    content: "종합검진 받고 결과가 나왔는데 수치들이 어떤 의미인지 궁금합니다",
    author: "최건강",
    createdAt: "2024-08-03T16:45:00",
    views: 198,
    comments: 15,
    likes: 22,
    category: "건강체크",
    isHot: true,
  },
];

const MESSAGE_DATA = [
  {
    id: 1,
    type: "emergency",
    message: "즉시 확인이 필요합니다. 안전을 위해 연락주세요!",
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    isRead: false,
    isConfirmed: false,
  },
  {
    id: 2,
    type: "normal",
    message: "약 복용 시간입니다. 물과 함께 드세요.",
    timestamp: new Date(Date.now() - 75 * 60000).toISOString(),
    isRead: true,
    isConfirmed: true,
  },
  {
    id: 3,
    type: "good",
    message: "오늘 하루도 건강하게 보내세요! 항상 응원하고 있어요.",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    isRead: true,
    isConfirmed: false,
  },
  {
    id: 4,
    type: "normal",
    message: "건강 체크 시간이에요. 혈압을 측정해주세요.",
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    isRead: false,
    isConfirmed: false,
  },
  {
    id: 5,
    type: "good",
    message: "컨디션이 좋아 보여서 기뻐요. 계속 잘 지내세요!",
    timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
    isRead: true,
    isConfirmed: true,
  },
  {
    id: 6,
    type: "normal",
    message: "오늘 날씨가 좋네요. 산책 한 번 다녀오시는 건 어떨까요?",
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    isRead: true,
    isConfirmed: false,
  },
];

const MESSAGES_DATA = [
  {
    id: 1,
    content: "물 좀 주세요.",
    isEditing: false,
    alertCycle: 15,
    status: "HIGH",
  },
  {
    id: 2,
    content: "간호사를 불러주세요.",
    isEditing: false,
    alertCycle: 5,
    status: "HIGH",
  },
  {
    id: 3,
    content: "목에 가래가 끼었습니다. 도와주세요.",
    isEditing: false,
    alertCycle: 10,
    status: "HIGH",
  },
  {
    id: 4,
    content: "체위를 바꿔주세요.",
    isEditing: false,
    alertCycle: 20,
    status: "MEDIUM",
  },
  {
    id: 5,
    content: "화장실에 가고 싶습니다.",
    isEditing: false,
    alertCycle: 15,
    status: "HIGH",
  },
  {
    id: 6,
    content: "TV 채널을 바꿔주세요.",
    isEditing: false,
    alertCycle: 60,
    status: "LOW",
  },
  {
    id: 7,
    content: "조명이 너무 밝습니다. 줄여주세요.",
    isEditing: false,
    alertCycle: 45,
    status: "LOW",
  },
  {
    id: 8,
    content: "추워요. 이불을 덮어주세요.",
    isEditing: false,
    alertCycle: 30,
    status: "MEDIUM",
  },
  {
    id: 9,
    content: "더워요. 창문을 열어주세요.",
    isEditing: false,
    alertCycle: 30,
    status: "MEDIUM",
  },
  {
    id: 10,
    content: "약 먹을 시간이에요.",
    isEditing: false,
    alertCycle: 120,
    status: "HIGH",
  },
];
export { BOARD_DATA, MESSAGE_DATA, MESSAGES_DATA };
